CC          ?= gcc
AR          ?= ar
FMT         ?= clang-format
VALGRIND    ?= valgrind
INSTALL     := install

INSTALL_DIR ?= /usr/local
MAN_DIR     ?= /usr/share/man/man3

LIBNAME     := lib<project>
LIBVERS     := 0.0.1
MANPAGE     := $(LIBNAME).3
